services:
  - type: web
    name: valandaicom-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "cd backend && gunicorn core.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        fromDatabase:
          name: valandaicom-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "valandaicom-backend.onrender.com"
      - key: SITE_URL
        value: "https://valandai.com"

databases:
  - name: valandaicom-db
    databaseName: personal_website
    user: admin
